from __future__ import annotations
from typing import Protocol, runtime_checkable
from memor.types import Artifact, Scope

@runtime_checkable
class Embedder(Protocol):
    dim: int
    def embed(self, texts: list[str]) -> list[list[float]]: ...

@runtime_checkable
class LLM(Protocol):
    def complete(self, prompt: str, *, max_tokens: int = 1024) -> str: ...

@runtime_checkable
class MemoryStore(Protocol):
    def add_artifacts(self, artifacts: list[Artifact], vectors: list[list[float]]) -> None: ...
    def add_edge(self, src_id: str, dst_id: str, type: str) -> None: ...
    def search(self, vector: list[float], scope: Scope, k: int) -> list[tuple[Artifact, float]]: ...
    def neighbors(self, ids: list[str], types: list[str], hops: int = 1) -> list[Artifact]: ...
    def deactivate(self, artifact_id: str, superseded_by: str) -> None: ...
