#!/usr/bin/env python3
"""Render captured terminal output to an SVG for the README.

A screenshot of a terminal is a PNG that cannot be searched, does not scale on a
retina display, and goes stale silently. An SVG of the same text stays crisp,
diffs as text in review, and is regenerated by re-running this script, so the
image in the README can be checked against the command that produced it.

Usage:
    memor doctor | python scripts/render_terminal_svg.py docs/images/doctor.svg
"""
from __future__ import annotations

import html
import sys

# Matches the dashboard's palette so the README reads as one product.
BG = "#0d1117"
FG = "#c9d1d9"
DIM = "#6e7681"
GREEN = "#3fb950"
YELLOW = "#d29922"
RED = "#f85149"
CYAN = "#39c5cf"

CHAR_W = 8.4
LINE_H = 20
PAD = 18


def colour_for(line: str) -> str:
    """Colour a line by its status marker, mirroring what the CLI signals."""
    stripped = line.strip()
    if stripped.startswith("ok "):
        return GREEN
    if stripped.startswith("!! "):
        return RED
    if stripped.startswith("-- "):
        return YELLOW
    if stripped.startswith("- "):
        return DIM
    if stripped.startswith(("agent", "$")):
        return CYAN
    return FG


def render(lines: list[str], title: str = "") -> str:
    body = [ln.rstrip("\n") for ln in lines]
    width = int(max((len(l) for l in body), default=60) * CHAR_W) + PAD * 2
    height = len(body) * LINE_H + PAD * 2 + 28

    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" '
        f'height="{height}" viewBox="0 0 {width} {height}">',
        f'<rect width="{width}" height="{height}" rx="10" fill="{BG}"/>',
        # Window chrome: three dots, so it reads as a terminal at a glance.
        f'<circle cx="20" cy="18" r="5" fill="#ff5f57"/>',
        f'<circle cx="38" cy="18" r="5" fill="#febc2e"/>',
        f'<circle cx="56" cy="18" r="5" fill="#28c840"/>',
    ]
    if title:
        out.append(
            f'<text x="76" y="22" font-family="ui-monospace,SFMono-Regular,Menlo,monospace"'
            f' font-size="12" fill="{DIM}">{html.escape(title)}</text>'
        )

    for i, line in enumerate(body):
        y = PAD + 28 + i * LINE_H
        out.append(
            f'<text x="{PAD}" y="{y}" font-family="ui-monospace,SFMono-Regular,Menlo,monospace"'
            f' font-size="13" fill="{colour_for(line)}" '
            f'xml:space="preserve">{html.escape(line)}</text>'
        )

    out.append("</svg>")
    return "\n".join(out)


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2
    dest = sys.argv[1]
    title = sys.argv[2] if len(sys.argv) > 2 else ""
    svg = render(sys.stdin.read().splitlines(), title=title)
    with open(dest, "w") as fh:
        fh.write(svg)
    print(f"wrote {dest}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
